# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 04:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['text'],
            },
        ),
        migrations.AddField(
            model_name='log',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.Todo'),
        ),
    ]
