# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=128)),
                ('datetime_update', models.DateTimeField(auto_now=True)),
                ('datetime_create', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[(b's', b'Stuff'), (b'a', b'Action'), (b'w', b'Waiting for'), (b'm', b'Maybe / Someday')], default=b's', max_length=1)),
                ('context', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.Context')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='things.Project')),
            ],
        ),
    ]
